/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ConsentManagerInterface extends Interface {
  getFunction(
    nameOrSignature: "consent" | "grantConsent" | "hasConsent" | "revokeConsent"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "ConsentGranted" | "ConsentRevoked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "consent",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "grantConsent",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "hasConsent",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeConsent",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "consent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "grantConsent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasConsent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "revokeConsent",
    data: BytesLike
  ): Result;
}

export namespace ConsentGrantedEvent {
  export type InputTuple = [patient: AddressLike, trialId: BigNumberish];
  export type OutputTuple = [patient: string, trialId: bigint];
  export interface OutputObject {
    patient: string;
    trialId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ConsentRevokedEvent {
  export type InputTuple = [patient: AddressLike, trialId: BigNumberish];
  export type OutputTuple = [patient: string, trialId: bigint];
  export interface OutputObject {
    patient: string;
    trialId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ConsentManager extends BaseContract {
  connect(runner?: ContractRunner | null): ConsentManager;
  waitForDeployment(): Promise<this>;

  interface: ConsentManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  consent: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;

  grantConsent: TypedContractMethod<
    [_trialId: BigNumberish],
    [void],
    "nonpayable"
  >;

  hasConsent: TypedContractMethod<
    [_patient: AddressLike, _trialId: BigNumberish],
    [boolean],
    "view"
  >;

  revokeConsent: TypedContractMethod<
    [_trialId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "consent"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "grantConsent"
  ): TypedContractMethod<[_trialId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "hasConsent"
  ): TypedContractMethod<
    [_patient: AddressLike, _trialId: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "revokeConsent"
  ): TypedContractMethod<[_trialId: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "ConsentGranted"
  ): TypedContractEvent<
    ConsentGrantedEvent.InputTuple,
    ConsentGrantedEvent.OutputTuple,
    ConsentGrantedEvent.OutputObject
  >;
  getEvent(
    key: "ConsentRevoked"
  ): TypedContractEvent<
    ConsentRevokedEvent.InputTuple,
    ConsentRevokedEvent.OutputTuple,
    ConsentRevokedEvent.OutputObject
  >;

  filters: {
    "ConsentGranted(address,uint256)": TypedContractEvent<
      ConsentGrantedEvent.InputTuple,
      ConsentGrantedEvent.OutputTuple,
      ConsentGrantedEvent.OutputObject
    >;
    ConsentGranted: TypedContractEvent<
      ConsentGrantedEvent.InputTuple,
      ConsentGrantedEvent.OutputTuple,
      ConsentGrantedEvent.OutputObject
    >;

    "ConsentRevoked(address,uint256)": TypedContractEvent<
      ConsentRevokedEvent.InputTuple,
      ConsentRevokedEvent.OutputTuple,
      ConsentRevokedEvent.OutputObject
    >;
    ConsentRevoked: TypedContractEvent<
      ConsentRevokedEvent.InputTuple,
      ConsentRevokedEvent.OutputTuple,
      ConsentRevokedEvent.OutputObject
    >;
  };
}
