/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace DataAccessLog {
  export type LogEntryStruct = {
    action: BigNumberish;
    trialId: BigNumberish;
    patientHash: BytesLike;
    timestamp: BigNumberish;
    performer: AddressLike;
  };

  export type LogEntryStructOutput = [
    action: bigint,
    trialId: bigint,
    patientHash: string,
    timestamp: bigint,
    performer: string
  ] & {
    action: bigint;
    trialId: bigint;
    patientHash: string;
    timestamp: bigint;
    performer: string;
  };
}

export interface DataAccessLogInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getLog"
      | "getLogCount"
      | "isAuthorizedLogger"
      | "logAction"
      | "logs"
      | "owner"
      | "setAuthorizedLogger"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "ActionLogged"): EventFragment;

  encodeFunctionData(
    functionFragment: "getLog",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLogCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isAuthorizedLogger",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "logAction",
    values: [BigNumberish, BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "logs", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setAuthorizedLogger",
    values: [AddressLike, boolean]
  ): string;

  decodeFunctionResult(functionFragment: "getLog", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getLogCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isAuthorizedLogger",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "logAction", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "logs", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAuthorizedLogger",
    data: BytesLike
  ): Result;
}

export namespace ActionLoggedEvent {
  export type InputTuple = [
    action: BigNumberish,
    trialId: BigNumberish,
    patientHash: BytesLike
  ];
  export type OutputTuple = [
    action: bigint,
    trialId: bigint,
    patientHash: string
  ];
  export interface OutputObject {
    action: bigint;
    trialId: bigint;
    patientHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DataAccessLog extends BaseContract {
  connect(runner?: ContractRunner | null): DataAccessLog;
  waitForDeployment(): Promise<this>;

  interface: DataAccessLogInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getLog: TypedContractMethod<
    [_index: BigNumberish],
    [DataAccessLog.LogEntryStructOutput],
    "view"
  >;

  getLogCount: TypedContractMethod<[], [bigint], "view">;

  isAuthorizedLogger: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  logAction: TypedContractMethod<
    [_action: BigNumberish, _trialId: BigNumberish, _patientHash: BytesLike],
    [void],
    "nonpayable"
  >;

  logs: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, string, bigint, string] & {
        action: bigint;
        trialId: bigint;
        patientHash: string;
        timestamp: bigint;
        performer: string;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  setAuthorizedLogger: TypedContractMethod<
    [_logger: AddressLike, _status: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getLog"
  ): TypedContractMethod<
    [_index: BigNumberish],
    [DataAccessLog.LogEntryStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getLogCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "isAuthorizedLogger"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "logAction"
  ): TypedContractMethod<
    [_action: BigNumberish, _trialId: BigNumberish, _patientHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "logs"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, string, bigint, string] & {
        action: bigint;
        trialId: bigint;
        patientHash: string;
        timestamp: bigint;
        performer: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setAuthorizedLogger"
  ): TypedContractMethod<
    [_logger: AddressLike, _status: boolean],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ActionLogged"
  ): TypedContractEvent<
    ActionLoggedEvent.InputTuple,
    ActionLoggedEvent.OutputTuple,
    ActionLoggedEvent.OutputObject
  >;

  filters: {
    "ActionLogged(uint8,uint256,bytes32)": TypedContractEvent<
      ActionLoggedEvent.InputTuple,
      ActionLoggedEvent.OutputTuple,
      ActionLoggedEvent.OutputObject
    >;
    ActionLogged: TypedContractEvent<
      ActionLoggedEvent.InputTuple,
      ActionLoggedEvent.OutputTuple,
      ActionLoggedEvent.OutputObject
    >;
  };
}
