/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface EligibilityEngineInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "applications"
      | "applyToTrial"
      | "automationContract"
      | "checkEligibility"
      | "confidentialProtocolId"
      | "consentManager"
      | "dataAccessLog"
      | "encryptedResults"
      | "encryptedScores"
      | "getEncryptedResult"
      | "getEncryptedScore"
      | "owner"
      | "patientRegistry"
      | "setAutomationContract"
      | "setDataAccessLog"
      | "trialAppliedPatients"
      | "trialManager"
      | "updateApplicationStatus"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ApplicationStatusUpdated"
      | "AppliedToTrial"
      | "EligibilityComputed"
      | "EligibilityScoreComputed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "applications",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "applyToTrial",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "automationContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "checkEligibility",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "consentManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "dataAccessLog",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "encryptedResults",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "encryptedScores",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedResult",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedScore",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "patientRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAutomationContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setDataAccessLog",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "trialAppliedPatients",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "trialManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateApplicationStatus",
    values: [BigNumberish, AddressLike, BigNumberish, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "applications",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "applyToTrial",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "automationContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkEligibility",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "consentManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dataAccessLog",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "encryptedResults",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "encryptedScores",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedResult",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedScore",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "patientRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAutomationContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDataAccessLog",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "trialAppliedPatients",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "trialManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateApplicationStatus",
    data: BytesLike
  ): Result;
}

export namespace ApplicationStatusUpdatedEvent {
  export type InputTuple = [
    patient: AddressLike,
    trialId: BigNumberish,
    status: BigNumberish,
    message: BytesLike
  ];
  export type OutputTuple = [
    patient: string,
    trialId: bigint,
    status: bigint,
    message: string
  ];
  export interface OutputObject {
    patient: string;
    trialId: bigint;
    status: bigint;
    message: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace AppliedToTrialEvent {
  export type InputTuple = [patient: AddressLike, trialId: BigNumberish];
  export type OutputTuple = [patient: string, trialId: bigint];
  export interface OutputObject {
    patient: string;
    trialId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EligibilityComputedEvent {
  export type InputTuple = [patient: AddressLike, trialId: BigNumberish];
  export type OutputTuple = [patient: string, trialId: bigint];
  export interface OutputObject {
    patient: string;
    trialId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace EligibilityScoreComputedEvent {
  export type InputTuple = [patient: AddressLike, trialId: BigNumberish];
  export type OutputTuple = [patient: string, trialId: bigint];
  export interface OutputObject {
    patient: string;
    trialId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface EligibilityEngine extends BaseContract {
  connect(runner?: ContractRunner | null): EligibilityEngine;
  waitForDeployment(): Promise<this>;

  interface: EligibilityEngineInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  applications: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [[bigint, string] & { status: bigint; encryptedMessage: string }],
    "view"
  >;

  applyToTrial: TypedContractMethod<
    [_trialId: BigNumberish],
    [void],
    "nonpayable"
  >;

  automationContract: TypedContractMethod<[], [string], "view">;

  checkEligibility: TypedContractMethod<
    [_patient: AddressLike, _trialId: BigNumberish],
    [string],
    "nonpayable"
  >;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  consentManager: TypedContractMethod<[], [string], "view">;

  dataAccessLog: TypedContractMethod<[], [string], "view">;

  encryptedResults: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  encryptedScores: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  getEncryptedResult: TypedContractMethod<
    [_patient: AddressLike, _trialId: BigNumberish],
    [string],
    "view"
  >;

  getEncryptedScore: TypedContractMethod<
    [_patient: AddressLike, _trialId: BigNumberish],
    [string],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  patientRegistry: TypedContractMethod<[], [string], "view">;

  setAutomationContract: TypedContractMethod<
    [_automation: AddressLike],
    [void],
    "nonpayable"
  >;

  setDataAccessLog: TypedContractMethod<
    [_log: AddressLike],
    [void],
    "nonpayable"
  >;

  trialAppliedPatients: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;

  trialManager: TypedContractMethod<[], [string], "view">;

  updateApplicationStatus: TypedContractMethod<
    [
      _trialId: BigNumberish,
      _patient: AddressLike,
      _status: BigNumberish,
      _message: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "applications"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [[bigint, string] & { status: bigint; encryptedMessage: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "applyToTrial"
  ): TypedContractMethod<[_trialId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "automationContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "checkEligibility"
  ): TypedContractMethod<
    [_patient: AddressLike, _trialId: BigNumberish],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "consentManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "dataAccessLog"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "encryptedResults"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "encryptedScores"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEncryptedResult"
  ): TypedContractMethod<
    [_patient: AddressLike, _trialId: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEncryptedScore"
  ): TypedContractMethod<
    [_patient: AddressLike, _trialId: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "patientRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setAutomationContract"
  ): TypedContractMethod<[_automation: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setDataAccessLog"
  ): TypedContractMethod<[_log: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "trialAppliedPatients"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "trialManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "updateApplicationStatus"
  ): TypedContractMethod<
    [
      _trialId: BigNumberish,
      _patient: AddressLike,
      _status: BigNumberish,
      _message: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ApplicationStatusUpdated"
  ): TypedContractEvent<
    ApplicationStatusUpdatedEvent.InputTuple,
    ApplicationStatusUpdatedEvent.OutputTuple,
    ApplicationStatusUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "AppliedToTrial"
  ): TypedContractEvent<
    AppliedToTrialEvent.InputTuple,
    AppliedToTrialEvent.OutputTuple,
    AppliedToTrialEvent.OutputObject
  >;
  getEvent(
    key: "EligibilityComputed"
  ): TypedContractEvent<
    EligibilityComputedEvent.InputTuple,
    EligibilityComputedEvent.OutputTuple,
    EligibilityComputedEvent.OutputObject
  >;
  getEvent(
    key: "EligibilityScoreComputed"
  ): TypedContractEvent<
    EligibilityScoreComputedEvent.InputTuple,
    EligibilityScoreComputedEvent.OutputTuple,
    EligibilityScoreComputedEvent.OutputObject
  >;

  filters: {
    "ApplicationStatusUpdated(address,uint256,uint8,bytes)": TypedContractEvent<
      ApplicationStatusUpdatedEvent.InputTuple,
      ApplicationStatusUpdatedEvent.OutputTuple,
      ApplicationStatusUpdatedEvent.OutputObject
    >;
    ApplicationStatusUpdated: TypedContractEvent<
      ApplicationStatusUpdatedEvent.InputTuple,
      ApplicationStatusUpdatedEvent.OutputTuple,
      ApplicationStatusUpdatedEvent.OutputObject
    >;

    "AppliedToTrial(address,uint256)": TypedContractEvent<
      AppliedToTrialEvent.InputTuple,
      AppliedToTrialEvent.OutputTuple,
      AppliedToTrialEvent.OutputObject
    >;
    AppliedToTrial: TypedContractEvent<
      AppliedToTrialEvent.InputTuple,
      AppliedToTrialEvent.OutputTuple,
      AppliedToTrialEvent.OutputObject
    >;

    "EligibilityComputed(address,uint256)": TypedContractEvent<
      EligibilityComputedEvent.InputTuple,
      EligibilityComputedEvent.OutputTuple,
      EligibilityComputedEvent.OutputObject
    >;
    EligibilityComputed: TypedContractEvent<
      EligibilityComputedEvent.InputTuple,
      EligibilityComputedEvent.OutputTuple,
      EligibilityComputedEvent.OutputObject
    >;

    "EligibilityScoreComputed(address,uint256)": TypedContractEvent<
      EligibilityScoreComputedEvent.InputTuple,
      EligibilityScoreComputedEvent.OutputTuple,
      EligibilityScoreComputedEvent.OutputObject
    >;
    EligibilityScoreComputed: TypedContractEvent<
      EligibilityScoreComputedEvent.InputTuple,
      EligibilityScoreComputedEvent.OutputTuple,
      EligibilityScoreComputedEvent.OutputObject
    >;
  };
}
