/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as stakingManagerSol from "./StakingManager.sol";
export type { stakingManagerSol };
import type * as test from "./test";
export type { test };
export type { ConfidentialETH } from "./ConfidentialETH";
export type { ConsentManager } from "./ConsentManager";
export type { DataAccessLog } from "./DataAccessLog";
export type { EligibilityEngine } from "./EligibilityEngine";
export type { MedVaultAutomation } from "./MedVaultAutomation";
export type { PatientRegistry } from "./PatientRegistry";
export type { SponsorIncentiveVault } from "./SponsorIncentiveVault";
export type { SponsorRegistry } from "./SponsorRegistry";
export type { TrialManager } from "./TrialManager";
export type { TrialMilestoneManager } from "./TrialMilestoneManager";
