/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace PatientRegistry {
  export type PatientStruct = {
    age: BytesLike;
    gender: BytesLike;
    weight: BytesLike;
    height: BytesLike;
    hasDiabetes: BytesLike;
    hbLevel: BytesLike;
    isSmoker: BytesLike;
    hasHypertension: BytesLike;
    exists: boolean;
  };

  export type PatientStructOutput = [
    age: string,
    gender: string,
    weight: string,
    height: string,
    hasDiabetes: string,
    hbLevel: string,
    isSmoker: string,
    hasHypertension: string,
    exists: boolean
  ] & {
    age: string;
    gender: string;
    weight: string;
    height: string;
    hasDiabetes: string;
    hbLevel: string;
    isSmoker: string;
    hasHypertension: string;
    exists: boolean;
  };
}

export interface PatientRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "authorizedEngine"
      | "confidentialProtocolId"
      | "dataAccessLog"
      | "getPatient"
      | "owner"
      | "setAuthorizedEngine"
      | "setDataAccessLog"
      | "submitEncryptedProfile"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "ProfileUpdated"): EventFragment;

  encodeFunctionData(
    functionFragment: "authorizedEngine",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "dataAccessLog",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPatient",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setAuthorizedEngine",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setDataAccessLog",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitEncryptedProfile",
    values: [
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike,
      BytesLike
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "authorizedEngine",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dataAccessLog",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPatient", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAuthorizedEngine",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDataAccessLog",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "submitEncryptedProfile",
    data: BytesLike
  ): Result;
}

export namespace ProfileUpdatedEvent {
  export type InputTuple = [patient: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [patient: string, timestamp: bigint];
  export interface OutputObject {
    patient: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PatientRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): PatientRegistry;
  waitForDeployment(): Promise<this>;

  interface: PatientRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  authorizedEngine: TypedContractMethod<[], [string], "view">;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  dataAccessLog: TypedContractMethod<[], [string], "view">;

  getPatient: TypedContractMethod<
    [_patient: AddressLike],
    [PatientRegistry.PatientStructOutput],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  setAuthorizedEngine: TypedContractMethod<
    [_engine: AddressLike],
    [void],
    "nonpayable"
  >;

  setDataAccessLog: TypedContractMethod<
    [_log: AddressLike],
    [void],
    "nonpayable"
  >;

  submitEncryptedProfile: TypedContractMethod<
    [
      _age: BytesLike,
      _ageProof: BytesLike,
      _gender: BytesLike,
      _genderProof: BytesLike,
      _weight: BytesLike,
      _weightProof: BytesLike,
      _height: BytesLike,
      _heightProof: BytesLike,
      _hasDiabetes: BytesLike,
      _diabetesProof: BytesLike,
      _hbLevel: BytesLike,
      _hbProof: BytesLike,
      _isSmoker: BytesLike,
      _isSmokerProof: BytesLike,
      _hasHypertension: BytesLike,
      _hasHypertensionProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "authorizedEngine"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "dataAccessLog"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getPatient"
  ): TypedContractMethod<
    [_patient: AddressLike],
    [PatientRegistry.PatientStructOutput],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setAuthorizedEngine"
  ): TypedContractMethod<[_engine: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setDataAccessLog"
  ): TypedContractMethod<[_log: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "submitEncryptedProfile"
  ): TypedContractMethod<
    [
      _age: BytesLike,
      _ageProof: BytesLike,
      _gender: BytesLike,
      _genderProof: BytesLike,
      _weight: BytesLike,
      _weightProof: BytesLike,
      _height: BytesLike,
      _heightProof: BytesLike,
      _hasDiabetes: BytesLike,
      _diabetesProof: BytesLike,
      _hbLevel: BytesLike,
      _hbProof: BytesLike,
      _isSmoker: BytesLike,
      _isSmokerProof: BytesLike,
      _hasHypertension: BytesLike,
      _hasHypertensionProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ProfileUpdated"
  ): TypedContractEvent<
    ProfileUpdatedEvent.InputTuple,
    ProfileUpdatedEvent.OutputTuple,
    ProfileUpdatedEvent.OutputObject
  >;

  filters: {
    "ProfileUpdated(address,uint256)": TypedContractEvent<
      ProfileUpdatedEvent.InputTuple,
      ProfileUpdatedEvent.OutputTuple,
      ProfileUpdatedEvent.OutputObject
    >;
    ProfileUpdated: TypedContractEvent<
      ProfileUpdatedEvent.InputTuple,
      ProfileUpdatedEvent.OutputTuple,
      ProfileUpdatedEvent.OutputObject
    >;
  };
}
