/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SponsorRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addSponsor"
      | "isVerifiedSponsor"
      | "owner"
      | "removeSponsor"
      | "sponsors"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "SponsorAdded" | "SponsorRemoved"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addSponsor",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "isVerifiedSponsor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeSponsor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sponsors",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "addSponsor", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isVerifiedSponsor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeSponsor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sponsors", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace SponsorAddedEvent {
  export type InputTuple = [sponsor: AddressLike, name: string];
  export type OutputTuple = [sponsor: string, name: string];
  export interface OutputObject {
    sponsor: string;
    name: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SponsorRemovedEvent {
  export type InputTuple = [sponsor: AddressLike];
  export type OutputTuple = [sponsor: string];
  export interface OutputObject {
    sponsor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SponsorRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): SponsorRegistry;
  waitForDeployment(): Promise<this>;

  interface: SponsorRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addSponsor: TypedContractMethod<
    [_sponsor: AddressLike, _name: string],
    [void],
    "nonpayable"
  >;

  isVerifiedSponsor: TypedContractMethod<
    [_sponsor: AddressLike],
    [boolean],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  removeSponsor: TypedContractMethod<
    [_sponsor: AddressLike],
    [void],
    "nonpayable"
  >;

  sponsors: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, boolean, bigint] & {
        name: string;
        verified: boolean;
        addedAt: bigint;
      }
    ],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [_newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addSponsor"
  ): TypedContractMethod<
    [_sponsor: AddressLike, _name: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isVerifiedSponsor"
  ): TypedContractMethod<[_sponsor: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "removeSponsor"
  ): TypedContractMethod<[_sponsor: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "sponsors"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, boolean, bigint] & {
        name: string;
        verified: boolean;
        addedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[_newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "SponsorAdded"
  ): TypedContractEvent<
    SponsorAddedEvent.InputTuple,
    SponsorAddedEvent.OutputTuple,
    SponsorAddedEvent.OutputObject
  >;
  getEvent(
    key: "SponsorRemoved"
  ): TypedContractEvent<
    SponsorRemovedEvent.InputTuple,
    SponsorRemovedEvent.OutputTuple,
    SponsorRemovedEvent.OutputObject
  >;

  filters: {
    "SponsorAdded(address,string)": TypedContractEvent<
      SponsorAddedEvent.InputTuple,
      SponsorAddedEvent.OutputTuple,
      SponsorAddedEvent.OutputObject
    >;
    SponsorAdded: TypedContractEvent<
      SponsorAddedEvent.InputTuple,
      SponsorAddedEvent.OutputTuple,
      SponsorAddedEvent.OutputObject
    >;

    "SponsorRemoved(address)": TypedContractEvent<
      SponsorRemovedEvent.InputTuple,
      SponsorRemovedEvent.OutputTuple,
      SponsorRemovedEvent.OutputObject
    >;
    SponsorRemoved: TypedContractEvent<
      SponsorRemovedEvent.InputTuple,
      SponsorRemovedEvent.OutputTuple,
      SponsorRemovedEvent.OutputObject
    >;
  };
}
