/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SponsorIncentiveVaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "automationContract"
      | "cETH"
      | "confidentialProtocolId"
      | "dataAccessLog"
      | "distribute"
      | "distributeMilestoneToParticipant"
      | "distributePartial"
      | "eligibilityEngine"
      | "fundTrial"
      | "getParticipantCount"
      | "getTotalDeposited"
      | "isDistributed"
      | "isPoolFunded"
      | "milestoneDistributed"
      | "milestoneManager"
      | "owner"
      | "participantMilestonePaid"
      | "registerParticipant"
      | "setAutomationContract"
      | "setDataAccessLog"
      | "setMilestoneManager"
      | "trialManager"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "IncentiveFunded"
      | "MilestoneRewardsDistributed"
      | "ParticipantRegistered"
      | "RewardClaimed"
      | "RewardsDistributed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "automationContract",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "cETH", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "dataAccessLog",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "distribute",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "distributeMilestoneToParticipant",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "distributePartial",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "eligibilityEngine",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "fundTrial",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getParticipantCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalDeposited",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isDistributed",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isPoolFunded",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "milestoneDistributed",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "milestoneManager",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "participantMilestonePaid",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerParticipant",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setAutomationContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setDataAccessLog",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setMilestoneManager",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "trialManager",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "automationContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "cETH", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dataAccessLog",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "distribute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "distributeMilestoneToParticipant",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "distributePartial",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "eligibilityEngine",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fundTrial", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getParticipantCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalDeposited",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isDistributed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isPoolFunded",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "milestoneDistributed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "milestoneManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "participantMilestonePaid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerParticipant",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAutomationContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setDataAccessLog",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMilestoneManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "trialManager",
    data: BytesLike
  ): Result;
}

export namespace IncentiveFundedEvent {
  export type InputTuple = [
    trialId: BigNumberish,
    sponsor: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [trialId: bigint, sponsor: string, amount: bigint];
  export interface OutputObject {
    trialId: bigint;
    sponsor: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MilestoneRewardsDistributedEvent {
  export type InputTuple = [
    trialId: BigNumberish,
    milestoneIndex: BigNumberish,
    shareWei: BigNumberish
  ];
  export type OutputTuple = [
    trialId: bigint,
    milestoneIndex: bigint,
    shareWei: bigint
  ];
  export interface OutputObject {
    trialId: bigint;
    milestoneIndex: bigint;
    shareWei: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ParticipantRegisteredEvent {
  export type InputTuple = [trialId: BigNumberish, participant: AddressLike];
  export type OutputTuple = [trialId: bigint, participant: string];
  export interface OutputObject {
    trialId: bigint;
    participant: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardClaimedEvent {
  export type InputTuple = [patient: AddressLike, amount: BigNumberish];
  export type OutputTuple = [patient: string, amount: bigint];
  export interface OutputObject {
    patient: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardsDistributedEvent {
  export type InputTuple = [
    trialId: BigNumberish,
    participantCount: BigNumberish,
    shareWei: BigNumberish
  ];
  export type OutputTuple = [
    trialId: bigint,
    participantCount: bigint,
    shareWei: bigint
  ];
  export interface OutputObject {
    trialId: bigint;
    participantCount: bigint;
    shareWei: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SponsorIncentiveVault extends BaseContract {
  connect(runner?: ContractRunner | null): SponsorIncentiveVault;
  waitForDeployment(): Promise<this>;

  interface: SponsorIncentiveVaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  automationContract: TypedContractMethod<[], [string], "view">;

  cETH: TypedContractMethod<[], [string], "view">;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  dataAccessLog: TypedContractMethod<[], [string], "view">;

  distribute: TypedContractMethod<
    [_trialId: BigNumberish],
    [void],
    "nonpayable"
  >;

  distributeMilestoneToParticipant: TypedContractMethod<
    [
      _trialId: BigNumberish,
      _participant: AddressLike,
      _milestoneIndex: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  distributePartial: TypedContractMethod<
    [_trialId: BigNumberish, _milestoneIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  eligibilityEngine: TypedContractMethod<[], [string], "view">;

  fundTrial: TypedContractMethod<[_trialId: BigNumberish], [void], "payable">;

  getParticipantCount: TypedContractMethod<
    [_trialId: BigNumberish],
    [bigint],
    "view"
  >;

  getTotalDeposited: TypedContractMethod<
    [_trialId: BigNumberish],
    [bigint],
    "view"
  >;

  isDistributed: TypedContractMethod<
    [_trialId: BigNumberish],
    [boolean],
    "view"
  >;

  isPoolFunded: TypedContractMethod<
    [_trialId: BigNumberish],
    [boolean],
    "view"
  >;

  milestoneDistributed: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [boolean],
    "view"
  >;

  milestoneManager: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  participantMilestonePaid: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike, arg2: BigNumberish],
    [boolean],
    "view"
  >;

  registerParticipant: TypedContractMethod<
    [_trialId: BigNumberish, _participant: AddressLike],
    [void],
    "nonpayable"
  >;

  setAutomationContract: TypedContractMethod<
    [_automation: AddressLike],
    [void],
    "nonpayable"
  >;

  setDataAccessLog: TypedContractMethod<
    [_dataAccessLog: AddressLike],
    [void],
    "nonpayable"
  >;

  setMilestoneManager: TypedContractMethod<
    [_milestoneManager: AddressLike],
    [void],
    "nonpayable"
  >;

  trialManager: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "automationContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "cETH"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "dataAccessLog"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "distribute"
  ): TypedContractMethod<[_trialId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "distributeMilestoneToParticipant"
  ): TypedContractMethod<
    [
      _trialId: BigNumberish,
      _participant: AddressLike,
      _milestoneIndex: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "distributePartial"
  ): TypedContractMethod<
    [_trialId: BigNumberish, _milestoneIndex: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "eligibilityEngine"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "fundTrial"
  ): TypedContractMethod<[_trialId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "getParticipantCount"
  ): TypedContractMethod<[_trialId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getTotalDeposited"
  ): TypedContractMethod<[_trialId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "isDistributed"
  ): TypedContractMethod<[_trialId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "isPoolFunded"
  ): TypedContractMethod<[_trialId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "milestoneDistributed"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "milestoneManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "participantMilestonePaid"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike, arg2: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerParticipant"
  ): TypedContractMethod<
    [_trialId: BigNumberish, _participant: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAutomationContract"
  ): TypedContractMethod<[_automation: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setDataAccessLog"
  ): TypedContractMethod<[_dataAccessLog: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setMilestoneManager"
  ): TypedContractMethod<
    [_milestoneManager: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "trialManager"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "IncentiveFunded"
  ): TypedContractEvent<
    IncentiveFundedEvent.InputTuple,
    IncentiveFundedEvent.OutputTuple,
    IncentiveFundedEvent.OutputObject
  >;
  getEvent(
    key: "MilestoneRewardsDistributed"
  ): TypedContractEvent<
    MilestoneRewardsDistributedEvent.InputTuple,
    MilestoneRewardsDistributedEvent.OutputTuple,
    MilestoneRewardsDistributedEvent.OutputObject
  >;
  getEvent(
    key: "ParticipantRegistered"
  ): TypedContractEvent<
    ParticipantRegisteredEvent.InputTuple,
    ParticipantRegisteredEvent.OutputTuple,
    ParticipantRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "RewardClaimed"
  ): TypedContractEvent<
    RewardClaimedEvent.InputTuple,
    RewardClaimedEvent.OutputTuple,
    RewardClaimedEvent.OutputObject
  >;
  getEvent(
    key: "RewardsDistributed"
  ): TypedContractEvent<
    RewardsDistributedEvent.InputTuple,
    RewardsDistributedEvent.OutputTuple,
    RewardsDistributedEvent.OutputObject
  >;

  filters: {
    "IncentiveFunded(uint256,address,uint256)": TypedContractEvent<
      IncentiveFundedEvent.InputTuple,
      IncentiveFundedEvent.OutputTuple,
      IncentiveFundedEvent.OutputObject
    >;
    IncentiveFunded: TypedContractEvent<
      IncentiveFundedEvent.InputTuple,
      IncentiveFundedEvent.OutputTuple,
      IncentiveFundedEvent.OutputObject
    >;

    "MilestoneRewardsDistributed(uint256,uint256,uint256)": TypedContractEvent<
      MilestoneRewardsDistributedEvent.InputTuple,
      MilestoneRewardsDistributedEvent.OutputTuple,
      MilestoneRewardsDistributedEvent.OutputObject
    >;
    MilestoneRewardsDistributed: TypedContractEvent<
      MilestoneRewardsDistributedEvent.InputTuple,
      MilestoneRewardsDistributedEvent.OutputTuple,
      MilestoneRewardsDistributedEvent.OutputObject
    >;

    "ParticipantRegistered(uint256,address)": TypedContractEvent<
      ParticipantRegisteredEvent.InputTuple,
      ParticipantRegisteredEvent.OutputTuple,
      ParticipantRegisteredEvent.OutputObject
    >;
    ParticipantRegistered: TypedContractEvent<
      ParticipantRegisteredEvent.InputTuple,
      ParticipantRegisteredEvent.OutputTuple,
      ParticipantRegisteredEvent.OutputObject
    >;

    "RewardClaimed(address,uint256)": TypedContractEvent<
      RewardClaimedEvent.InputTuple,
      RewardClaimedEvent.OutputTuple,
      RewardClaimedEvent.OutputObject
    >;
    RewardClaimed: TypedContractEvent<
      RewardClaimedEvent.InputTuple,
      RewardClaimedEvent.OutputTuple,
      RewardClaimedEvent.OutputObject
    >;

    "RewardsDistributed(uint256,uint256,uint256)": TypedContractEvent<
      RewardsDistributedEvent.InputTuple,
      RewardsDistributedEvent.OutputTuple,
      RewardsDistributedEvent.OutputObject
    >;
    RewardsDistributed: TypedContractEvent<
      RewardsDistributedEvent.InputTuple,
      RewardsDistributedEvent.OutputTuple,
      RewardsDistributedEvent.OutputObject
    >;
  };
}
