/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace TrialMilestoneManager {
  export type MilestoneStruct = {
    name: string;
    weightBps: BigNumberish;
    deadline: BigNumberish;
  };

  export type MilestoneStructOutput = [
    name: string,
    weightBps: bigint,
    deadline: bigint
  ] & { name: string; weightBps: bigint; deadline: bigint };
}

export interface TrialMilestoneManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "completeMilestone"
      | "getMilestones"
      | "getParticipantProgress"
      | "owner"
      | "participantProgress"
      | "setMilestones"
      | "setTrialManager"
      | "trialManager"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "MilestoneCompleted"
      | "MilestonesSet"
      | "TrialManagerUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "completeMilestone",
    values: [BigNumberish, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getMilestones",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getParticipantProgress",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "participantProgress",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setMilestones",
    values: [BigNumberish, string[], BigNumberish[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "setTrialManager",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "trialManager",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "completeMilestone",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMilestones",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getParticipantProgress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "participantProgress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setMilestones",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTrialManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "trialManager",
    data: BytesLike
  ): Result;
}

export namespace MilestoneCompletedEvent {
  export type InputTuple = [
    trialId: BigNumberish,
    patient: AddressLike,
    milestoneIndex: BigNumberish
  ];
  export type OutputTuple = [
    trialId: bigint,
    patient: string,
    milestoneIndex: bigint
  ];
  export interface OutputObject {
    trialId: bigint;
    patient: string;
    milestoneIndex: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MilestonesSetEvent {
  export type InputTuple = [
    trialId: BigNumberish,
    milestoneCount: BigNumberish
  ];
  export type OutputTuple = [trialId: bigint, milestoneCount: bigint];
  export interface OutputObject {
    trialId: bigint;
    milestoneCount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TrialManagerUpdatedEvent {
  export type InputTuple = [oldManager: AddressLike, newManager: AddressLike];
  export type OutputTuple = [oldManager: string, newManager: string];
  export interface OutputObject {
    oldManager: string;
    newManager: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TrialMilestoneManager extends BaseContract {
  connect(runner?: ContractRunner | null): TrialMilestoneManager;
  waitForDeployment(): Promise<this>;

  interface: TrialMilestoneManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  completeMilestone: TypedContractMethod<
    [
      _trialId: BigNumberish,
      _patient: AddressLike,
      _milestoneIndex: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getMilestones: TypedContractMethod<
    [_trialId: BigNumberish],
    [TrialMilestoneManager.MilestoneStructOutput[]],
    "view"
  >;

  getParticipantProgress: TypedContractMethod<
    [_trialId: BigNumberish, _patient: AddressLike],
    [bigint],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  participantProgress: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;

  setMilestones: TypedContractMethod<
    [
      _trialId: BigNumberish,
      _names: string[],
      _weights: BigNumberish[],
      _deadlines: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;

  setTrialManager: TypedContractMethod<
    [_newTrialManager: AddressLike],
    [void],
    "nonpayable"
  >;

  trialManager: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "completeMilestone"
  ): TypedContractMethod<
    [
      _trialId: BigNumberish,
      _patient: AddressLike,
      _milestoneIndex: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getMilestones"
  ): TypedContractMethod<
    [_trialId: BigNumberish],
    [TrialMilestoneManager.MilestoneStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getParticipantProgress"
  ): TypedContractMethod<
    [_trialId: BigNumberish, _patient: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "participantProgress"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "setMilestones"
  ): TypedContractMethod<
    [
      _trialId: BigNumberish,
      _names: string[],
      _weights: BigNumberish[],
      _deadlines: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTrialManager"
  ): TypedContractMethod<[_newTrialManager: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "trialManager"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "MilestoneCompleted"
  ): TypedContractEvent<
    MilestoneCompletedEvent.InputTuple,
    MilestoneCompletedEvent.OutputTuple,
    MilestoneCompletedEvent.OutputObject
  >;
  getEvent(
    key: "MilestonesSet"
  ): TypedContractEvent<
    MilestonesSetEvent.InputTuple,
    MilestonesSetEvent.OutputTuple,
    MilestonesSetEvent.OutputObject
  >;
  getEvent(
    key: "TrialManagerUpdated"
  ): TypedContractEvent<
    TrialManagerUpdatedEvent.InputTuple,
    TrialManagerUpdatedEvent.OutputTuple,
    TrialManagerUpdatedEvent.OutputObject
  >;

  filters: {
    "MilestoneCompleted(uint256,address,uint256)": TypedContractEvent<
      MilestoneCompletedEvent.InputTuple,
      MilestoneCompletedEvent.OutputTuple,
      MilestoneCompletedEvent.OutputObject
    >;
    MilestoneCompleted: TypedContractEvent<
      MilestoneCompletedEvent.InputTuple,
      MilestoneCompletedEvent.OutputTuple,
      MilestoneCompletedEvent.OutputObject
    >;

    "MilestonesSet(uint256,uint256)": TypedContractEvent<
      MilestonesSetEvent.InputTuple,
      MilestonesSetEvent.OutputTuple,
      MilestonesSetEvent.OutputObject
    >;
    MilestonesSet: TypedContractEvent<
      MilestonesSetEvent.InputTuple,
      MilestonesSetEvent.OutputTuple,
      MilestonesSetEvent.OutputObject
    >;

    "TrialManagerUpdated(address,address)": TypedContractEvent<
      TrialManagerUpdatedEvent.InputTuple,
      TrialManagerUpdatedEvent.OutputTuple,
      TrialManagerUpdatedEvent.OutputObject
    >;
    TrialManagerUpdated: TypedContractEvent<
      TrialManagerUpdatedEvent.InputTuple,
      TrialManagerUpdatedEvent.OutputTuple,
      TrialManagerUpdatedEvent.OutputObject
    >;
  };
}
