/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace TrialManager {
  export type TrialStruct = {
    name: string;
    phase: string;
    location: string;
    compensation: string;
    sponsor: AddressLike;
    active: boolean;
    minAge: BigNumberish;
    maxAge: BigNumberish;
    requiresDiabetes: boolean;
    minHb: BigNumberish;
    genderRequirement: BigNumberish;
    minHeight: BigNumberish;
    maxWeight: BigNumberish;
    requiresNonSmoker: boolean;
    requiresNormalBP: boolean;
    endTime: BigNumberish;
  };

  export type TrialStructOutput = [
    name: string,
    phase: string,
    location: string,
    compensation: string,
    sponsor: string,
    active: boolean,
    minAge: bigint,
    maxAge: bigint,
    requiresDiabetes: boolean,
    minHb: bigint,
    genderRequirement: bigint,
    minHeight: bigint,
    maxWeight: bigint,
    requiresNonSmoker: boolean,
    requiresNormalBP: boolean,
    endTime: bigint
  ] & {
    name: string;
    phase: string;
    location: string;
    compensation: string;
    sponsor: string;
    active: boolean;
    minAge: bigint;
    maxAge: bigint;
    requiresDiabetes: boolean;
    minHb: bigint;
    genderRequirement: bigint;
    minHeight: bigint;
    maxWeight: bigint;
    requiresNonSmoker: boolean;
    requiresNormalBP: boolean;
    endTime: bigint;
  };
}

export interface TrialManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "automationContract"
      | "createTrial"
      | "deactivateTrial"
      | "getTrial"
      | "owner"
      | "setAutomationContract"
      | "setSponsorName"
      | "setSponsorRegistry"
      | "sponsorNames"
      | "sponsorRegistry"
      | "trialCounter"
      | "trials"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "SponsorNameUpdated"
      | "SponsorRegistryUpdated"
      | "TrialCreated"
      | "TrialDeactivated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "automationContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createTrial",
    values: [
      string,
      string,
      string,
      string,
      BigNumberish,
      BigNumberish,
      boolean,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      boolean,
      boolean,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "deactivateTrial",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTrial",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setAutomationContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setSponsorName",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "setSponsorRegistry",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sponsorNames",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sponsorRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "trialCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "trials",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "automationContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createTrial",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deactivateTrial",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getTrial", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setAutomationContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSponsorName",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setSponsorRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sponsorNames",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sponsorRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "trialCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "trials", data: BytesLike): Result;
}

export namespace SponsorNameUpdatedEvent {
  export type InputTuple = [sponsor: AddressLike, name: string];
  export type OutputTuple = [sponsor: string, name: string];
  export interface OutputObject {
    sponsor: string;
    name: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SponsorRegistryUpdatedEvent {
  export type InputTuple = [newRegistry: AddressLike];
  export type OutputTuple = [newRegistry: string];
  export interface OutputObject {
    newRegistry: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TrialCreatedEvent {
  export type InputTuple = [
    trialId: BigNumberish,
    sponsor: AddressLike,
    name: string,
    endTime: BigNumberish
  ];
  export type OutputTuple = [
    trialId: bigint,
    sponsor: string,
    name: string,
    endTime: bigint
  ];
  export interface OutputObject {
    trialId: bigint;
    sponsor: string;
    name: string;
    endTime: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TrialDeactivatedEvent {
  export type InputTuple = [trialId: BigNumberish];
  export type OutputTuple = [trialId: bigint];
  export interface OutputObject {
    trialId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TrialManager extends BaseContract {
  connect(runner?: ContractRunner | null): TrialManager;
  waitForDeployment(): Promise<this>;

  interface: TrialManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  automationContract: TypedContractMethod<[], [string], "view">;

  createTrial: TypedContractMethod<
    [
      _name: string,
      _phase: string,
      _location: string,
      _compensation: string,
      _minAge: BigNumberish,
      _maxAge: BigNumberish,
      _requiresDiabetes: boolean,
      _minHb: BigNumberish,
      _genderReq: BigNumberish,
      _minHeight: BigNumberish,
      _maxWeight: BigNumberish,
      _requiresNonSmoker: boolean,
      _requiresNormalBP: boolean,
      _duration: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  deactivateTrial: TypedContractMethod<
    [_trialId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getTrial: TypedContractMethod<
    [_trialId: BigNumberish],
    [TrialManager.TrialStructOutput],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  setAutomationContract: TypedContractMethod<
    [_automation: AddressLike],
    [void],
    "nonpayable"
  >;

  setSponsorName: TypedContractMethod<[_name: string], [void], "nonpayable">;

  setSponsorRegistry: TypedContractMethod<
    [_registry: AddressLike],
    [void],
    "nonpayable"
  >;

  sponsorNames: TypedContractMethod<[arg0: AddressLike], [string], "view">;

  sponsorRegistry: TypedContractMethod<[], [string], "view">;

  trialCounter: TypedContractMethod<[], [bigint], "view">;

  trials: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        string,
        string,
        boolean,
        bigint,
        bigint,
        boolean,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean,
        bigint
      ] & {
        name: string;
        phase: string;
        location: string;
        compensation: string;
        sponsor: string;
        active: boolean;
        minAge: bigint;
        maxAge: bigint;
        requiresDiabetes: boolean;
        minHb: bigint;
        genderRequirement: bigint;
        minHeight: bigint;
        maxWeight: bigint;
        requiresNonSmoker: boolean;
        requiresNormalBP: boolean;
        endTime: bigint;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "automationContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "createTrial"
  ): TypedContractMethod<
    [
      _name: string,
      _phase: string,
      _location: string,
      _compensation: string,
      _minAge: BigNumberish,
      _maxAge: BigNumberish,
      _requiresDiabetes: boolean,
      _minHb: BigNumberish,
      _genderReq: BigNumberish,
      _minHeight: BigNumberish,
      _maxWeight: BigNumberish,
      _requiresNonSmoker: boolean,
      _requiresNormalBP: boolean,
      _duration: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "deactivateTrial"
  ): TypedContractMethod<[_trialId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getTrial"
  ): TypedContractMethod<
    [_trialId: BigNumberish],
    [TrialManager.TrialStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setAutomationContract"
  ): TypedContractMethod<[_automation: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setSponsorName"
  ): TypedContractMethod<[_name: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setSponsorRegistry"
  ): TypedContractMethod<[_registry: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "sponsorNames"
  ): TypedContractMethod<[arg0: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "sponsorRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "trialCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "trials"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        string,
        string,
        string,
        string,
        string,
        boolean,
        bigint,
        bigint,
        boolean,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        boolean,
        bigint
      ] & {
        name: string;
        phase: string;
        location: string;
        compensation: string;
        sponsor: string;
        active: boolean;
        minAge: bigint;
        maxAge: bigint;
        requiresDiabetes: boolean;
        minHb: bigint;
        genderRequirement: bigint;
        minHeight: bigint;
        maxWeight: bigint;
        requiresNonSmoker: boolean;
        requiresNormalBP: boolean;
        endTime: bigint;
      }
    ],
    "view"
  >;

  getEvent(
    key: "SponsorNameUpdated"
  ): TypedContractEvent<
    SponsorNameUpdatedEvent.InputTuple,
    SponsorNameUpdatedEvent.OutputTuple,
    SponsorNameUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "SponsorRegistryUpdated"
  ): TypedContractEvent<
    SponsorRegistryUpdatedEvent.InputTuple,
    SponsorRegistryUpdatedEvent.OutputTuple,
    SponsorRegistryUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TrialCreated"
  ): TypedContractEvent<
    TrialCreatedEvent.InputTuple,
    TrialCreatedEvent.OutputTuple,
    TrialCreatedEvent.OutputObject
  >;
  getEvent(
    key: "TrialDeactivated"
  ): TypedContractEvent<
    TrialDeactivatedEvent.InputTuple,
    TrialDeactivatedEvent.OutputTuple,
    TrialDeactivatedEvent.OutputObject
  >;

  filters: {
    "SponsorNameUpdated(address,string)": TypedContractEvent<
      SponsorNameUpdatedEvent.InputTuple,
      SponsorNameUpdatedEvent.OutputTuple,
      SponsorNameUpdatedEvent.OutputObject
    >;
    SponsorNameUpdated: TypedContractEvent<
      SponsorNameUpdatedEvent.InputTuple,
      SponsorNameUpdatedEvent.OutputTuple,
      SponsorNameUpdatedEvent.OutputObject
    >;

    "SponsorRegistryUpdated(address)": TypedContractEvent<
      SponsorRegistryUpdatedEvent.InputTuple,
      SponsorRegistryUpdatedEvent.OutputTuple,
      SponsorRegistryUpdatedEvent.OutputObject
    >;
    SponsorRegistryUpdated: TypedContractEvent<
      SponsorRegistryUpdatedEvent.InputTuple,
      SponsorRegistryUpdatedEvent.OutputTuple,
      SponsorRegistryUpdatedEvent.OutputObject
    >;

    "TrialCreated(uint256,address,string,uint256)": TypedContractEvent<
      TrialCreatedEvent.InputTuple,
      TrialCreatedEvent.OutputTuple,
      TrialCreatedEvent.OutputObject
    >;
    TrialCreated: TypedContractEvent<
      TrialCreatedEvent.InputTuple,
      TrialCreatedEvent.OutputTuple,
      TrialCreatedEvent.OutputObject
    >;

    "TrialDeactivated(uint256)": TypedContractEvent<
      TrialDeactivatedEvent.InputTuple,
      TrialDeactivatedEvent.OutputTuple,
      TrialDeactivatedEvent.OutputObject
    >;
    TrialDeactivated: TypedContractEvent<
      TrialDeactivatedEvent.InputTuple,
      TrialDeactivatedEvent.OutputTuple,
      TrialDeactivatedEvent.OutputObject
    >;
  };
}
