/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IERC20 } from "./IERC20";
export type { IWrappedTokenGatewayV3 } from "./IWrappedTokenGatewayV3";
export type { StakingManager } from "./StakingManager";
