/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  ConsentManager,
  ConsentManagerInterface,
} from "../../contracts/ConsentManager";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "patient",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "trialId",
        type: "uint256",
      },
    ],
    name: "ConsentGranted",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "patient",
        type: "address",
      },
      {
        indexed: true,
        internalType: "uint256",
        name: "trialId",
        type: "uint256",
      },
    ],
    name: "ConsentRevoked",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    name: "consent",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_trialId",
        type: "uint256",
      },
    ],
    name: "grantConsent",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_patient",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "_trialId",
        type: "uint256",
      },
    ],
    name: "hasConsent",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_trialId",
        type: "uint256",
      },
    ],
    name: "revokeConsent",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

const _bytecode =
  "0x6080806040523460155761016a908161001a8239f35b5f80fdfe60806040526004361015610011575f80fd5b5f3560e01c806316a0042c146100df5780632a26de8514610084578063663334f8146100455763b0a2cc6314610045575f80fd5b346100805761005336610137565b9060018060a01b03165f525f60205260405f20905f52602052602060ff60405f2054166040519015158152f35b5f80fd5b3461008057602036600319011261008057600435335f525f60205260405f20815f5260205260405f20600160ff19825416179055337ffa2079192eb4ccb7613c7caeba634279b187c2f49dafc0c4819bbc5f878ac3055f80a3005b3461008057602036600319011261008057600435335f525f60205260405f20815f5260205260405f2060ff198154169055337f988f76ef7977a3c8ed258b6edb689399775fa491cc7367bb03d44d8d55af79a85f80a3005b6040906003190112610080576004356001600160a01b038116810361008057906024359056fea164736f6c634300081b000a";

type ConsentManagerConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ConsentManagerConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ConsentManager__factory extends ContractFactory {
  constructor(...args: ConsentManagerConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      ConsentManager & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): ConsentManager__factory {
    return super.connect(runner) as ConsentManager__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ConsentManagerInterface {
    return new Interface(_abi) as ConsentManagerInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ConsentManager {
    return new Contract(address, _abi, runner) as unknown as ConsentManager;
  }
}
