/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IWrappedTokenGatewayV3,
  IWrappedTokenGatewayV3Interface,
} from "../../../contracts/StakingManager.sol/IWrappedTokenGatewayV3";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "pool",
        type: "address",
      },
      {
        internalType: "address",
        name: "onBehalfOf",
        type: "address",
      },
      {
        internalType: "uint16",
        name: "referralCode",
        type: "uint16",
      },
    ],
    name: "depositETH",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "pool",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
    ],
    name: "withdrawETH",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IWrappedTokenGatewayV3__factory {
  static readonly abi = _abi;
  static createInterface(): IWrappedTokenGatewayV3Interface {
    return new Interface(_abi) as IWrappedTokenGatewayV3Interface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IWrappedTokenGatewayV3 {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IWrappedTokenGatewayV3;
  }
}
