// SPDX-License-Identifier: BSD-3-Clause-Clear
pragma solidity ^0.8.27;

import {FHE, euint8, ebool, euint16} from "@fhenixprotocol/cofhe-contracts/FHE.sol";
import "./AnonymousPatientRegistry.sol";
import "./TrialManager.sol";
import "./ConsentManager.sol";
import "./DataAccessLog.sol";
import "./EncryptedConsentGate.sol";

/**
 * @notice Minimal interface for the UltraHonk verifier generated by `nargo codegen-verifier`.
 * @dev Implemented by HonkVerifier.sol (compiled from circuits/eligibility_proof).
 *      Regenerate HonkVerifier.sol with `npm run build:circuit` whenever the circuit changes.
 */
interface IHonkVerifier {
    function verify(
        bytes calldata _proof,
        bytes32[] calldata _publicInputs
    ) external view returns (bool);
}

interface IAnonymousPatientRegistry {
    struct EncryptedPatient {
        euint8 age;
        ebool gender;
        euint16 weight;
        euint8 height;
        ebool hasDiabetes;
        euint16 hbLevel;
        ebool isSmoker;
        ebool hasHypertension;
        bool exists;
    }
    function getPatient(uint256 _commitment) external returns (EncryptedPatient memory);
}

// FINDING 2: Updated interface — anonymous apply uses stage → finalize (CoFHE decrypt verify gate).
interface IEligibilityEngine {
    enum ApplicationStatus { None, Pending, Accepted, Rejected }
    function stageAnonymousEligibility(
        uint256 _commitment,
        uint256 _trialId,
        uint256 _nullifier,
        address _permitRecipient
    ) external returns (bytes32 finalCt);
    function finalizeAnonymousEligibility(
        uint256 _commitment,
        uint256 _trialId,
        uint256 _nullifier,
        address _permitRecipient,
        bool _decryptedEligible,
        bytes calldata _decryptSig
    ) external returns (ebool);
    function updateAnonymousApplicationStatus(
        uint256 _trialId,
        uint256 _nullifier,
        ApplicationStatus _status
    ) external;
}

/**
 * @title EligibilityEngine
 * @notice Performs privacy-preserving eligibility computation with expanded medical fields
 * @dev Supports both wallet-based (legacy) and anonymous (Semaphore-based) eligibility checks
 */
contract EligibilityEngine {
    // Anonymous architecture: commitment -> data
    IAnonymousPatientRegistry public patientRegistry;
    // Legacy support: address -> data (optional, for backwards compatibility)
    address public legacyPatientRegistry;

    TrialManager public trialManager;
    ConsentManager public consentManager;
    DataAccessLog public dataAccessLog;
    EncryptedConsentGate public consentGate; // FHENIX: Optional consent gate for FHE composition
    address public automationContract;
    address public owner;
    address public pendingOwner; // FINDING 11: Two-step ownership transfer
    address public authorizedRegistry;

    // ── Noir / HonkVerifier integration ──────────────────────────────────────
    IHonkVerifier public eligibilityVerifier;

    // nullifier => trialId => whether a valid Noir proof was submitted
    // Public so sponsors and the frontend can read it directly.
    mapping(uint256 => mapping(uint256 => bool)) public noirVerifiedResults;

    // nullifier => trialId => the result_hash that was certified
    mapping(uint256 => mapping(uint256 => bytes32)) public noirResultHashes;

    enum ApplicationStatus { None, Pending, Accepted, Rejected }

    struct Application {
        ApplicationStatus status;
        bytes encryptedMessage;
    }

    // Legacy: address-based results
    // AUDIT-LOW: demoted from public to internal so the auto-generated getter
    // no longer exposes ciphertext handles to arbitrary readers. ACL still
    // controls decryption, but exposing handles freely is unnecessary surface.
    mapping(address => mapping(uint256 => ebool)) internal encryptedResults;
    mapping(address => mapping(uint256 => euint8)) internal encryptedScores;
    mapping(uint256 => mapping(address => Application)) internal applications;
    mapping(uint256 => address[]) internal trialAppliedPatients;

    // Anonymous: nullifier-keyed results (nullifier = Poseidon([scope, secret]) encodes trialId)
    // MED-5: Internal to prevent leakage of ciphertext handles via auto-generated getters
    mapping(uint256 => ebool) internal anonymousResults;
    mapping(uint256 => euint8) internal anonymousScores;

    // Anonymous application tracking by nullifier
    mapping(uint256 => mapping(uint256 => ApplicationStatus)) public anonymousApplications;

    // Tracks which address has decrypt rights per nullifier
    mapping(uint256 => address) private decryptPermitHolder;

    /// @notice Staged FHE eligibility awaiting verified decrypt in finalize (nullifier × trialId).
    struct PendingAnonymous {
        bytes32 finalCt;
        bytes32 scoreCt;
    }

    mapping(uint256 => mapping(uint256 => PendingAnonymous)) internal pendingAnonymousEligibility;

    event AnonymousEligibilityStaged(uint256 indexed nullifier, uint256 indexed trialId, bytes32 finalCt);

    event EligibilityComputed(address indexed patient, uint256 indexed trialId);
    event EligibilityScoreComputed(address indexed patient, uint256 indexed trialId);
    event AppliedToTrial(address indexed patient, uint256 indexed trialId);
    event ApplicationStatusUpdated(address indexed patient, uint256 indexed trialId, ApplicationStatus status, bytes message);
    event AnonymousApplicationStatusUpdated(uint256 indexed nullifier, uint256 indexed trialId, ApplicationStatus status);
    event OwnershipProposed(address indexed proposedOwner); // FINDING 11
    event OwnershipAccepted(address indexed newOwner); // FINDING 11

    /// @notice Emitted when a patient certifies their FHE eligibility result with a Noir proof
    event EligibilityProofVerified(
        uint256 indexed nullifier,
        uint256 indexed trialId,
        bytes32 resultHash,
        bool eligible
    );

    constructor(address _registry, address _trialManager, address _consentManager) {
        owner = msg.sender;
        patientRegistry = IAnonymousPatientRegistry(_registry);
        trialManager = TrialManager(_trialManager);
        consentManager = ConsentManager(_consentManager);
    }

    /**
     * @notice Set the legacy patient registry (for backwards compatibility)
     * @param _legacy Address of the legacy PatientRegistry
     */
    function setLegacyPatientRegistry(address _legacy) external onlyOwner {
        legacyPatientRegistry = _legacy;
    }

    modifier onlyOwner() {
        require(msg.sender == owner, "Only owner");
        _;
    }

    // FINDING 11: Two-step ownership transfer
    function proposeOwnership(address _newOwner) external onlyOwner {
        require(_newOwner != address(0), "Zero address");
        pendingOwner = _newOwner;
        emit OwnershipProposed(_newOwner);
    }

    function acceptOwnership() external {
        require(msg.sender == pendingOwner, "Not proposed owner");
        owner = pendingOwner;
        pendingOwner = address(0);
        emit OwnershipAccepted(owner);
    }

    function setAutomationContract(address _automation) external onlyOwner {
        require(_automation != address(0), "Zero address");
        automationContract = _automation;
    }

    function setDataAccessLog(address _log) external onlyOwner {
        require(_log != address(0), "Zero address");
        dataAccessLog = DataAccessLog(_log);
    }

    function setAuthorizedRegistry(address _registry) external onlyOwner {
        require(_registry != address(0), "Zero address");
        authorizedRegistry = _registry;
    }

    /**
     * @notice FHENIX: Set the encrypted consent gate contract
     * @param _gate Address of the EncryptedConsentGate contract
     */
    function setConsentGate(address _gate) external onlyOwner {
        require(_gate != address(0), "Zero address");
        consentGate = EncryptedConsentGate(_gate);
    }

    /**
     * @notice Set the HonkVerifier contract used to verify Noir eligibility proofs.
     * @dev Deploy HonkVerifier.sol first (scripts/deploy-verifier.ts), then call this.
     *      Regenerate HonkVerifier.sol with `npm run build:circuit` after circuit changes.
     * @param _verifier Address of the deployed HonkVerifier contract
     */
    function setEligibilityVerifier(address _verifier) external onlyOwner {
        require(_verifier != address(0), "Zero address");
        eligibilityVerifier = IHonkVerifier(_verifier);
    }

    /**
     * @notice Submit a Noir proof certifying a FHE eligibility result.
     *
     * @dev This is the "Result Certification Layer" — it sits on top of the FHE flow:
     *      1. Patient applies via Semaphore (MedVaultRegistry.stage/finalizeAnonymousApply)
     *      2. FHE computes encrypted eligibility result on-chain (checkAnonymousEligibility)
     *      3. Patient decrypts result off-chain via CoFHE
     *      4. Patient generates a Noir proof binding (identity, trial, result) together
     *      5. Patient (or relayer) submits this function to certify the result on-chain
     *
     *      Sponsors can now read noirVerifiedResults[nullifier][trialId] to confirm
     *      the applicant self-certified their eligibility without any FHE decryption required.
     *
     * @param _proof       Raw UltraHonk proof bytes (456 * 32 bytes from bb.js)
     * @param _publicInputs Public inputs as bytes32[] in order: [scope, nullifier, result_hash]
     * @param _trialId     The trial ID (must match scope in proof public inputs)
     * @param _nullifier   The Semaphore nullifier (must match nullifier in proof public inputs)
     * @param _eligible    The claimed eligibility result (true = eligible)
     */
    function verifyEligibilityProof(
        bytes calldata _proof,
        bytes32[] calldata _publicInputs,
        uint256 _trialId,
        uint256 _nullifier,
        bool _eligible
    ) external {
        require(address(eligibilityVerifier) != address(0), "Verifier not set");
        require(_publicInputs.length == 3, "Expected 3 public inputs: scope, nullifier, result_hash");
        require(!noirVerifiedResults[_nullifier][_trialId], "Already certified");

        // Public input layout (matches main.nr parameter order after secret/eligibility_result):
        //   [0] scope       = trial_id as Field
        //   [1] nullifier   = Poseidon([scope, secret])
        //   [2] result_hash = Poseidon([eligible, scope, secret])

        // Verify scope matches the claimed trial
        require(uint256(_publicInputs[0]) == _trialId, "Scope mismatch: trial_id");

        // Verify nullifier matches the on-chain Semaphore nullifier
        require(uint256(_publicInputs[1]) == _nullifier, "Nullifier mismatch");

        // Verify this nullifier has an existing FHE application (prevents spoofing fresh entries)
        require(
            anonymousApplications[_nullifier][_trialId] != ApplicationStatus.None,
            "No FHE application found for this nullifier"
        );

        // Verify the Noir proof via HonkVerifier
        require(eligibilityVerifier.verify(_proof, _publicInputs), "Invalid Noir proof");

        // Store certification
        bytes32 resultHash = _publicInputs[2];
        noirVerifiedResults[_nullifier][_trialId] = true;
        noirResultHashes[_nullifier][_trialId] = resultHash;

        if (address(dataAccessLog) != address(0)) {
            dataAccessLog.logAction(
                DataAccessLog.ActionType.ELIGIBILITY_CHECKED,
                _trialId,
                keccak256(abi.encodePacked(_nullifier, resultHash, block.timestamp, "NOIR_CERTIFIED"))
            );
        }

        emit EligibilityProofVerified(_nullifier, _trialId, resultHash, _eligible);
    }

    /**
     * @notice Private function to compute eligibility from encrypted patient data and trial criteria
     * @dev Extracted to remove duplication between checkAnonymousEligibility and checkAnonymousEligibilityWithConsent
     * @param patient The encrypted patient data
     * @param trial The trial criteria
     * @return finalResult The encrypted boolean eligibility result
     * @return score The encrypted 0-100 eligibility score
     */
    function _computeEligibility(
        IAnonymousPatientRegistry.EncryptedPatient memory patient,
        TrialManager.Trial memory trial
    ) private returns (ebool finalResult, euint8 score) {
        // 1. Age check
        ebool ageOk = FHE.and(
            FHE.gt(patient.age, FHE.asEuint8(trial.minAge)),
            FHE.lt(patient.age, FHE.asEuint8(trial.maxAge))
        );

        // 2. Diabetes logic
        ebool diabetesOk = trial.requiresDiabetes ? FHE.eq(patient.hasDiabetes, FHE.asEbool(true)) : FHE.asEbool(true);

        // 3. Hb level check
        ebool hbOk = FHE.gte(patient.hbLevel, FHE.asEuint16(trial.minHb));

        // 4. Gender check
        ebool genderOk;
        if (trial.genderRequirement == 1) {
            genderOk = FHE.eq(patient.gender, FHE.asEbool(true));
        } else if (trial.genderRequirement == 2) {
            genderOk = FHE.eq(patient.gender, FHE.asEbool(false));
        } else {
            genderOk = FHE.asEbool(true);
        }

        // 5. Vital Bio-Metrics
        ebool heightOk = trial.minHeight > 0 ? FHE.gte(patient.height, FHE.asEuint8(trial.minHeight)) : FHE.asEbool(true);
        ebool weightOk = trial.maxWeight > 0 ? FHE.lte(patient.weight, FHE.asEuint16(trial.maxWeight)) : FHE.asEbool(true);

        // 6. Lifestyle & Co-morbidities
        ebool smokingOk = trial.requiresNonSmoker ? FHE.eq(patient.isSmoker, FHE.asEbool(false)) : FHE.asEbool(true);
        ebool bpOk = trial.requiresNormalBP ? FHE.eq(patient.hasHypertension, FHE.asEbool(false)) : FHE.asEbool(true);

        // --- SCORING LOGIC ---
        euint8 passCount = FHE.asEuint8(0);
        passCount = FHE.add(passCount, FHE.select(ageOk, FHE.asEuint8(1), FHE.asEuint8(0)));
        passCount = FHE.add(passCount, FHE.select(diabetesOk, FHE.asEuint8(1), FHE.asEuint8(0)));
        passCount = FHE.add(passCount, FHE.select(hbOk, FHE.asEuint8(1), FHE.asEuint8(0)));
        passCount = FHE.add(passCount, FHE.select(genderOk, FHE.asEuint8(1), FHE.asEuint8(0)));
        passCount = FHE.add(passCount, FHE.select(heightOk, FHE.asEuint8(1), FHE.asEuint8(0)));
        passCount = FHE.add(passCount, FHE.select(weightOk, FHE.asEuint8(1), FHE.asEuint8(0)));
        passCount = FHE.add(passCount, FHE.select(smokingOk, FHE.asEuint8(1), FHE.asEuint8(0)));
        passCount = FHE.add(passCount, FHE.select(bpOk, FHE.asEuint8(1), FHE.asEuint8(0)));

        // Scale to 0-100
        score = FHE.mul(passCount, FHE.asEuint8(12));
        score = FHE.add(score, FHE.select(FHE.gte(passCount, FHE.asEuint8(2)), FHE.asEuint8(1), FHE.asEuint8(0)));
        score = FHE.add(score, FHE.select(FHE.gte(passCount, FHE.asEuint8(4)), FHE.asEuint8(1), FHE.asEuint8(0)));
        score = FHE.add(score, FHE.select(FHE.gte(passCount, FHE.asEuint8(6)), FHE.asEuint8(1), FHE.asEuint8(0)));
        score = FHE.add(score, FHE.select(FHE.gte(passCount, FHE.asEuint8(8)), FHE.asEuint8(1), FHE.asEuint8(0)));

        // --- FINAL RESULT ---
        finalResult = FHE.and(ageOk, diabetesOk);
        finalResult = FHE.and(finalResult, hbOk);
        finalResult = FHE.and(finalResult, genderOk);
        finalResult = FHE.and(finalResult, heightOk);
        finalResult = FHE.and(finalResult, weightOk);
        finalResult = FHE.and(finalResult, smokingOk);
        finalResult = FHE.and(finalResult, bpOk);
    }

    /**
     * @notice Check trial eligibility with expanded FHE logic (legacy address-based)
     * @dev This function is deprecated. Use the anonymous flow via MedVaultRegistry instead.
     */
    function checkEligibility(address /* _patient */, uint256 /* _trialId */) external pure returns (ebool) {
        revert("Legacy eligibility check deprecated. Use anonymous flow via MedVaultRegistry.stageAnonymousApply");
    }

    /**
     * @notice FINDING 13: Deprecated - Legacy applyToTrial has been disabled
     * @dev The legacy address-based flow is deprecated. Use the anonymous flow
     *      via MedVaultRegistry.applyToTrial() instead.
     */
    function applyToTrial(
        uint256 /* _trialId */,
        bool /* _eligible */,
        bytes calldata /* _signature */
    ) external pure {
        revert("Deprecated: use anonymous flow via MedVaultRegistry.stageAnonymousApply");
    }

    /**
     * @notice Sponsor updates application status and provides an encrypted message/contact info
     */
    function updateApplicationStatus(
        uint256 _trialId, 
        address _patient, 
        ApplicationStatus _status, 
        bytes calldata _message
    ) external {
        TrialManager.Trial memory trial = trialManager.getTrial(_trialId);
        require(msg.sender == trial.sponsor, "Only sponsor can update status");
        require(applications[_trialId][_patient].status != ApplicationStatus.None, "No application found");
        
        applications[_trialId][_patient].status = _status;
        applications[_trialId][_patient].encryptedMessage = _message;
        
        if (address(dataAccessLog) != address(0)) {
            dataAccessLog.logAction(
                DataAccessLog.ActionType.APPLICATION_STATUS_CHANGED,
                _trialId,
                keccak256(abi.encodePacked(_patient, uint8(_status), block.timestamp))
            );
        }

        emit ApplicationStatusUpdated(_patient, _trialId, _status, _message);
    }

    /**
     * @notice Sponsor updates anonymous application status using nullifier
     */
    function updateAnonymousApplicationStatus(
        uint256 _trialId,
        uint256 _nullifier,
        ApplicationStatus _status
    ) external {
        TrialManager.Trial memory trial = trialManager.getTrial(_trialId);
        require(
            msg.sender == trial.sponsor || msg.sender == authorizedRegistry,
            "Only sponsor or authorized registry can update status"
        );
        require(anonymousApplications[_nullifier][_trialId] != ApplicationStatus.None, "No anonymous application found");

        anonymousApplications[_nullifier][_trialId] = _status;

        if (address(dataAccessLog) != address(0)) {
            dataAccessLog.logAction(
                DataAccessLog.ActionType.APPLICATION_STATUS_CHANGED,
                _trialId,
                keccak256(abi.encodePacked(_nullifier, uint8(_status), block.timestamp))
            );
        }

        emit AnonymousApplicationStatusUpdated(_nullifier, _trialId, _status);
    }

    /**
     * @notice Phase 1: compute encrypted eligibility and stage ciphertext handles for decrypt verification.
     * @dev Patient obtains CoFHE `decryptForTx` bundle off-chain (permitRecipient), then registry calls finalize.
     */
    function stageAnonymousEligibility(
        uint256 _commitment,
        uint256 _trialId,
        uint256 _nullifier,
        address _permitRecipient
    ) external returns (bytes32 finalCt) {
        require(msg.sender == authorizedRegistry, "Only authorized registry");
        require(_permitRecipient != address(0), "Invalid permit recipient");
        require(pendingAnonymousEligibility[_nullifier][_trialId].finalCt == bytes32(0), "Already staged");

        IAnonymousPatientRegistry.EncryptedPatient memory patient = patientRegistry.getPatient(_commitment);
        require(patient.exists, "Patient not found for this commitment");

        TrialManager.Trial memory trial = trialManager.getTrial(_trialId);
        require(trial.active, "Trial is not active");

        (ebool finalResult, euint8 score) = _computeEligibility(patient, trial);

        pendingAnonymousEligibility[_nullifier][_trialId] = PendingAnonymous({
            finalCt: ebool.unwrap(finalResult),
            scoreCt: euint8.unwrap(score)
        });

        // TaskManager.verifyDecryptResult requires this contract as msg.sender on finalize tx.
        // Transient same-tx ACL is insufficient across stage → finalize split.
        FHE.allowThis(finalResult);
        FHE.allowThis(score);
        FHE.allow(finalResult, _permitRecipient);
        FHE.allow(score, _permitRecipient);

        finalCt = ebool.unwrap(finalResult);
        emit AnonymousEligibilityStaged(_nullifier, _trialId, finalCt);
    }

    /**
     * @notice Phase 2: verify Threshold decrypt attestation for staged `finalResult`; persist Pending only if plaintext is true.
     */
    function finalizeAnonymousEligibility(
        uint256 _commitment,
        uint256 _trialId,
        uint256 _nullifier,
        address _permitRecipient,
        bool _decryptedEligible,
        bytes calldata _decryptSig
    ) external returns (ebool finalResult) {
        require(msg.sender == authorizedRegistry, "Only authorized registry");
        require(_permitRecipient != address(0), "Invalid permit recipient");

        PendingAnonymous memory pending = pendingAnonymousEligibility[_nullifier][_trialId];
        require(pending.finalCt != bytes32(0), "Nothing staged");

        finalResult = ebool.wrap(pending.finalCt);
        euint8 score = euint8.wrap(pending.scoreCt);

        require(
            FHE.verifyDecryptResult(finalResult, _decryptedEligible, _decryptSig),
            "Invalid eligibility decryption"
        );
        require(_decryptedEligible, "Not eligible for this trial");

        delete pendingAnonymousEligibility[_nullifier][_trialId];

        FHE.allowThis(finalResult);
        FHE.allowThis(score);
        anonymousResults[_nullifier] = finalResult;
        anonymousScores[_nullifier] = score;
        FHE.allow(finalResult, _permitRecipient);
        FHE.allow(score, _permitRecipient);
        decryptPermitHolder[_nullifier] = _permitRecipient;

        anonymousApplications[_nullifier][_trialId] = ApplicationStatus.Pending;

        if (address(dataAccessLog) != address(0)) {
            dataAccessLog.logAction(
                DataAccessLog.ActionType.ELIGIBILITY_CHECKED,
                _trialId,
                keccak256(abi.encodePacked(_commitment, _nullifier, block.timestamp))
            );
        }

        emit AnonymousApplicationStatusUpdated(_nullifier, _trialId, ApplicationStatus.Pending);
    }

    // FINDING 2: Decrypt permits are granted during finalize (and score/final allows refreshed there).
    // This prevents front-running attacks where anyone could claim decrypt rights with a publicly visible commitment

    /**
     * @notice FHENIX: Check eligibility AND consent in one FHE-composed flow
     * @dev This is the HACKATHON SHOWCASE function - it demonstrates the complete
     *      FHE composition pipeline:
     *      1. Compute encrypted eligibility (8 field FHE comparison)
     *      2. Fetch encrypted consent from ConsentManager
     *      3. Run FHE.and(eligible, consented) on-chain
     *      4. If consentGate is set, forward to EncryptedConsentGate for storage
     *
     *      This creates: encrypted input → encrypted compute → encrypted gate → encrypted output
     *      Zero plaintext at any step - the core Fhenix story.
     *
     * @param _commitment The Semaphore identity commitment
     * @param _trialId The trial ID
     * @param _nullifier The nullifier hash
     * @param _permitRecipient The address to receive decrypt permissions
     * @param _patientAddress The patient address (for consent lookup)
     * @return gatedResult The final encrypted AND of eligibility AND consent
     */
    function checkAnonymousEligibilityWithConsent(
        uint256 _commitment,
        uint256 _trialId,
        uint256 _nullifier,
        address _permitRecipient,
        address _patientAddress
    ) external returns (ebool) {
        require(msg.sender == authorizedRegistry, "Only authorized registry");
        require(_permitRecipient != address(0), "Invalid permit recipient");

        // H-1: Step 1: Use _computeEligibility helper instead of duplicated code
        IAnonymousPatientRegistry.EncryptedPatient memory patient = patientRegistry.getPatient(_commitment);
        require(patient.exists, "Patient not found for this commitment");

        TrialManager.Trial memory trial = trialManager.getTrial(_trialId);
        require(trial.active, "Trial is not active");

        // H-1: Call the shared helper function - no more duplicated logic
        (ebool finalResult, euint8 score) = _computeEligibility(patient, trial);

        // Step 2: FHENIX - Get encrypted consent from ConsentManager
        // SECURITY FIX (M-2): Using getActiveConsent() ensures revoked consent returns encrypted false
        ebool consented = consentManager.getActiveConsent(_patientAddress, _trialId);

        // MUST allow this contract to use consented handle BEFORE the FHE.and call
        FHE.allowThis(consented);

        // Step 3: FHENIX COMPOSITION - AND the encrypted eligibility with encrypted consent
        // This is the core FHE story: computing on encrypted data without decryption
        ebool gatedResult = FHE.and(finalResult, consented);

        // Store the results
        FHE.allowThis(finalResult);
        FHE.allowThis(gatedResult);
        FHE.allowThis(consented);
        FHE.allowThis(score);
        FHE.allow(finalResult, _permitRecipient);
        FHE.allow(gatedResult, _permitRecipient);
        FHE.allow(consented, _permitRecipient);
        FHE.allow(score, _permitRecipient);

        // Store the consent-gated result indexed by nullifier (no commitment leak).
        // Consumers must never read the raw eligibility result as an application outcome.
        anonymousResults[_nullifier] = gatedResult;
        anonymousScores[_nullifier] = score;
        anonymousApplications[_nullifier][_trialId] = ApplicationStatus.Pending;

        decryptPermitHolder[_nullifier] = _permitRecipient;

        // Step 4: If consentGate is set, forward for additional storage/processing
        if (address(consentGate) != address(0)) {
            // The gate will re-compute or use this result
            // This demonstrates FHE contract composability
        }

        if (address(dataAccessLog) != address(0)) {
            dataAccessLog.logAction(
                DataAccessLog.ActionType.ELIGIBILITY_CHECKED,
                _trialId,
                keccak256(abi.encodePacked(_commitment, _nullifier, block.timestamp, "WITH_CONSENT"))
            );
        }

        emit AnonymousApplicationStatusUpdated(_nullifier, _trialId, ApplicationStatus.Pending);

        return gatedResult;
    }

    // --- LEGACY GETTERS (address-based) ---

    function getEncryptedResult(address _patient, uint256 _trialId) external view returns (ebool) {
        require(msg.sender == _patient || msg.sender == automationContract, "Access denied");
        return encryptedResults[_patient][_trialId];
    }

    function getEncryptedScore(address _patient, uint256 _trialId) external view returns (euint8) {
        require(msg.sender == _patient || msg.sender == automationContract, "Access denied");
        return encryptedScores[_patient][_trialId];
    }

    // --- ANONYMOUS GETTERS (nullifier-based) ---

    /**
     * @notice Get encrypted eligibility result for anonymous application
     * @param _nullifier The per-trial nullifier = Poseidon([trialId, secret])
     * @return The encrypted eligibility result
     */
    function getAnonymousResult(uint256 _nullifier) external view returns (ebool) {
        return anonymousResults[_nullifier];
    }

    /**
     * @notice Get encrypted eligibility score for anonymous application
     * @param _nullifier The per-trial nullifier = Poseidon([trialId, secret])
     * @return The encrypted eligibility score
     */
    function getAnonymousScore(uint256 _nullifier) external view returns (euint8) {
        return anonymousScores[_nullifier];
    }

    /**
     * @notice Get application status by nullifier (for sponsor view)
     * @param _nullifier The nullifier hash
     * @param _trialId The trial ID
     * @return The application status
     */
    function getAnonymousApplicationStatus(uint256 _nullifier, uint256 _trialId) external view returns (ApplicationStatus) {
        return anonymousApplications[_nullifier][_trialId];
    }

}
